# Generated by Django 4.1 on 2022-10-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_image"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="CardItem", new_name="CartItem",),
    ]
